//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMobileBackEnd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalFlowRecord
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid WaitApprovalID { get; set; }
        public int ApprovalTypeValue { get; set; }
        public System.Guid FlowID { get; set; }
        public System.Guid FlowNodeID { get; set; }
        public string Context { get; set; }
        public bool IsCompleted { get; set; }
        public int ApprovalRecordStatusValue { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
        public System.Guid CreateUid { get; set; }
        public System.Guid UpdateUid { get; set; }
    }
}
