//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMobileBackEnd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColdStorage
    {
        public ColdStorage()
        {
            this.Fans = new HashSet<Fan>();
        }
    
        public System.Guid Id { get; set; }
        public string DocumentNumber { get; set; }
        public System.Guid PurchaserId { get; set; }
        public string VerificationCharger { get; set; }
        public string VerificationExeChanger { get; set; }
        public string Keeper { get; set; }
        public string DiviceKeeper { get; set; }
        public string QualityKeeper { get; set; }
        public string MaintainKeeper { get; set; }
        public int StorageSetTypeValue { get; set; }
        public string OutEnviroment { get; set; }
        public string SetPostion { get; set; }
        public System.DateTime StartedDatetime { get; set; }
        public decimal StorageLength { get; set; }
        public decimal StorageWidth { get; set; }
        public decimal StorageHeight { get; set; }
        public decimal StorageVolumn { get; set; }
        public decimal DoorLength { get; set; }
        public decimal DoorWidth { get; set; }
        public decimal DoorHeight { get; set; }
        public string ThermalInsuMaterial { get; set; }
        public string ThermalSystemFactory { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
        public System.Guid CreateUid { get; set; }
        public System.Guid UpdateUid { get; set; }
        public string DataDate { get; set; }
    
        public virtual Purchaser Purchaser { get; set; }
        public virtual ICollection<Fan> Fans { get; set; }
    }
}
