//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMobileBackEnd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColdStoreVerifySolution
    {
        public System.Guid Id { get; set; }
        public string DocumentNumber { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid VerificationId { get; set; }
        public System.Guid ColdStorageId { get; set; }
        public System.DateTime VTStartTime { get; set; }
        public System.DateTime VTStopTime { get; set; }
        public System.DateTime DataAnaStartTime { get; set; }
        public System.DateTime DataAnaStopTime { get; set; }
        public System.DateTime InternalAuditStartTime { get; set; }
        public System.DateTime InternalAuditStopTime { get; set; }
        public int stationPointAvg { get; set; }
        public int stationPointSpe { get; set; }
        public System.DateTime EnvTempTestStartTime { get; set; }
        public System.DateTime EnvTempTestStopTime { get; set; }
        public decimal EnvMaxTemp { get; set; }
        public decimal EnvMinTemp { get; set; }
        public decimal EnvAvgTemp { get; set; }
        public System.DateTime FullLoadStartTime { get; set; }
        public System.DateTime FullLoadStopTime { get; set; }
        public System.DateTime OpenDoorTestStartTime { get; set; }
        public System.DateTime OpenDoorTestStopTime { get; set; }
        public decimal OpenDoorTestTemp { get; set; }
        public System.DateTime OpenDoorTime { get; set; }
        public string CardNo1 { get; set; }
        public string CardNo2 { get; set; }
        public string TerminalNo1 { get; set; }
        public string TerminalNo2 { get; set; }
        public decimal AvgDifferCTNo1 { get; set; }
        public decimal AvgDifferCTNo2 { get; set; }
        public decimal AvgDifferCTMax { get; set; }
        public System.DateTime PowerCutStartTime { get; set; }
        public System.DateTime PowerCutStopTime { get; set; }
        public decimal PowerCutTemp { get; set; }
        public int PowerCutThermoTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
        public System.Guid CreateUid { get; set; }
        public System.Guid UpdateUid { get; set; }
    }
}
