//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMobileBackEnd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUser
    {
        public CUser()
        {
            this.RoleWithUsers = new HashSet<RoleWithUser>();
        }
    
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public string Pwd { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.Guid PositionId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
        public System.Guid CreateUid { get; set; }
        public System.Guid UpdateUid { get; set; }
        public bool IsLocked { get; set; }
        public System.Guid PurchaserId { get; set; }
        public bool IsCompanyAdmin { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<RoleWithUser> RoleWithUsers { get; set; }
    }
}
