//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMobileBackEnd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.CUsers = new HashSet<CUser>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Memo { get; set; }
        public int GenderValue { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string EduBg { get; set; }
        public string GraduateFrom { get; set; }
        public string Major { get; set; }
        public int JobExperienceYears { get; set; }
        public System.DateTime OfferDate { get; set; }
        public bool IsMarried { get; set; }
        public string BirthPlace { get; set; }
        public string SID { get; set; }
        public System.Guid DepartmentId { get; set; }
        public int OnDutyValue { get; set; }
        public System.Guid PositionId { get; set; }
        public string Tel { get; set; }
        public string Tel2 { get; set; }
        public string Address { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
        public System.Guid CreateUid { get; set; }
        public System.Guid UpdateUid { get; set; }
        public bool IsCustomer { get; set; }
        public System.Guid PurchaserId { get; set; }
    
        public virtual ICollection<CUser> CUsers { get; set; }
    }
}
