//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMobileBackEnd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncubatorVerification
    {
        public System.Guid Id { get; set; }
        public string DocumentNumber { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid VerificationId { get; set; }
        public System.DateTime VTStartTime { get; set; }
        public System.DateTime VTStopTime { get; set; }
        public decimal EnvMaxTemp { get; set; }
        public decimal EnvMinTemp { get; set; }
        public decimal EnvAvgTemp { get; set; }
        public System.Guid IncubatorId { get; set; }
        public string VTProperty { get; set; }
        public System.DateTime UnpackTestStartTime { get; set; }
        public System.DateTime UnpackTestStopTime { get; set; }
        public System.DateTime TestStartTime { get; set; }
        public System.DateTime TestStopTime { get; set; }
        public string OuterEnvironment { get; set; }
        public string TestCard { get; set; }
        public string AverageDeviation { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
        public System.Guid CreateUid { get; set; }
        public System.Guid UpdateUid { get; set; }
        public string VTAddress { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
    }
}
