//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMobileBackEnd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incubator
    {
        public System.Guid Id { get; set; }
        public System.Guid PurchaserId { get; set; }
        public string VerificationCharger { get; set; }
        public string VerificationExeChanger { get; set; }
        public string Keeper { get; set; }
        public string QualityKeeper { get; set; }
        public bool Deleted { get; set; }
        public string SN { get; set; }
        public string BrandModel { get; set; }
        public string Volume { get; set; }
        public string Accendant { get; set; }
        public string ExternalSize { get; set; }
        public string InternalSize { get; set; }
        public string Weight { get; set; }
        public string WallThickness { get; set; }
        public string ExternalMaterial { get; set; }
        public string InternalMaterial { get; set; }
        public string IceBrand { get; set; }
        public string IceCount { get; set; }
        public System.Guid CreateUid { get; set; }
        public System.Guid UpdateUid { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string DataDate { get; set; }
        public string ProductDate { get; set; }
    
        public virtual Purchaser Purchaser { get; set; }
    }
}
