//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMobileBackEnd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefrigeratorVerifySolution
    {
        public System.Guid Id { get; set; }
        public string DocumentNumber { get; set; }
        public System.Guid ContractId { get; set; }
        public System.Guid VerificationId { get; set; }
        public System.Guid RefrigeratorId { get; set; }
        public string stationPointAvg { get; set; }
        public string stationPointSpe { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Deleted { get; set; }
        public System.Guid CreateUid { get; set; }
        public System.Guid UpdateUid { get; set; }
        public System.DateTime PlanVerifyDate { get; set; }
        public System.DateTime VerifyDate { get; set; }
        public int VerifyCharacter { get; set; }
    }
}
